=== kieransimkin/TangleNet-ProtocolSchema/NRFProtocol.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://dealing.ninja/NRFProtocol" xmlns="http://dealing.ninja/NRFProtocol" xmlns:nrf="http://dealing.ninja/NRFProtocol"  elementFormDefault="qualified" attributeFormDefault="unqualified" >
	<xs:element name="NRFProtocol">
		<xs:complexType>
			<xs:all>
				<xs:element ref="nrf:BitfieldTypes" />
				<xs:element ref="nrf:EnumerationTypes" />
				<xs:element ref="nrf:Types" />
				<xs:element ref="nrf:NRFPacket" />
				<xs:element ref="nrf:MessageTypes" />
			</xs:all>
			<xs:attribute name="noNamespaceSchemaLocation" type="String" />
		</xs:complexType>
		<xs:key name="BitfieldTypeID">
			<xs:selector xpath="BitfieldTypes/BitfieldType" />
			<xs:field xpath="@ID" />
		</xs:key>
		<xs:key name="EnumerationTypeID">
			<xs:selector xpath="EnumerationTypes/EnumerationType" />
			<xs:field xpath="@ID" />
		</xs:key>
		<xs:key name="TypeID">
			<xs:selector xpath="Types/Type" />
			<xs:field xpath="@ID" />
		</xs:key>
		<xs:keyref name="TypeIDRef" refer="TypeID">
			<xs:selector xpath="*" />
			<xs:field xpath="@DataTypeID" />
		</xs:keyref>
		<xs:keyref name="EnumerationTypeIDRef" refer="EnumerationTypeID">
			<xs:selector xpath="./EnumerationType" />
			<xs:field xpath="@EnumerationTypeID" />
		</xs:keyref>
		<xs:keyref name="BitfieldTypeIDRef" refer="BitfieldTypeID">
			<xs:selector xpath="BitfieldType" />
			<xs:field xpath="@BitfieldTypeID" />
		</xs:keyref>
		<xs:key name="MessageTypeID">
			<xs:selector xpath="MessageTypes/MessageType" />
			<xs:field xpath="@ID" />
		</xs:key>
		<xs:keyref name="MessageTypeIDRef" refer="MessageTypeID">
			<xs:selector xpath="MessageType" />
			<xs:field xpath="@MessageTypeID" />
		</xs:keyref>
	</xs:element>
	<xs:simpleType name="String">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Token">
		<xs:restriction base="xs:NMTOKEN" />
	</xs:simpleType>
	<xs:simpleType name="Shekel">
		<xs:restriction base="xs:unsignedInt" />
	</xs:simpleType>
	<xs:simpleType name="SubType">
		<xs:restriction base="xs:NMTOKEN" />
	</xs:simpleType>
	<xs:simpleType name="CodeNameType">
		<xs:restriction base="xs:NMTOKEN" />
	</xs:simpleType>
	<xs:simpleType name="DataTypeID">
		<xs:restriction base="xs:NMTOKEN" />
	</xs:simpleType>
	<xs:simpleType name="EnumerationTypeID">
		<xs:restriction base="xs:NMTOKEN" />
	</xs:simpleType>
	<xs:simpleType name="BitfieldTypeID">
		<xs:restriction base="xs:NMTOKEN" />
	</xs:simpleType>
	<xs:simpleType name="MessageTypeID">
		<xs:restriction base="xs:NMTOKEN" />
	</xs:simpleType>
	<xs:element name="BitfieldTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nrf:BitfieldType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BitfieldType">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="String" />
				<xs:element name="CodeName" type="CodeNameType" />
				<xs:element name="Description" type="String" />
				<xs:element name="Bits">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Bit" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="String" minOccurs='0' maxOccurs='1'/>
										<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="ID" type="Token" use="required" />
									<xs:attribute name="CodeName" type="CodeNameType" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Width" type="Shekel" use="optional" default="1" />
			<xs:attribute name="ID" type="Token" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="EnumerationTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="EnumerationType" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="String" />
							<xs:element name="CodeName" type="CodeNameType" />
							<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
							<xs:element name="Options">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Option" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Name" type="String" minOccurs='0' maxOccurs='1' />
													<!-- TODO XXX name is not really optional -->
													<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
												</xs:sequence>
												<xs:attribute name="ID" type="Token" use="required" />
												<xs:attribute name="CodeName" type="CodeNameType" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
			<xs:attribute name="ID" type="Token" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Types">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Type" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="String" />
							<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
							<xs:element name="CType" type="String" />
							<xs:element name="CodeName" type="CodeNameType" />
							<xs:element name="DefaultWidth" type="Shekel" minOccurs="0" maxOccurs="1" default="1" />
							<xs:element name="Constraints">
								<xs:complexType>
									<xs:all>
									<xs:element name="MaxWidth" type="Shekel" minOccurs="0" maxOccurs="1" />
									<xs:element name="MinWidth" type="Shekel" minOccurs="0" maxOccurs="1" />
									<xs:element name="InvalidWidths" minOccurs="0" maxOccurs="1">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="InvalidWidth" type="Shekel" maxOccurs="unbounded" />
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="ValidWidths" minOccurs="0" maxOccurs="1">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="ValidWidth" type="Shekel" maxOccurs="unbounded" />
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="Values" minOccurs="0" maxOccurs="1">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Value" maxOccurs="unbounded">
													<xs:complexType>
														<xs:simpleContent>
															<xs:extension base="Token">
																<xs:attribute name="ID" type="Token" use="required" />
															</xs:extension>
														</xs:simpleContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="Attributes" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Attribute" maxOccurs="unbounded">
											<xs:complexType>
												<xs:all>
													<xs:element name="Name" type="String" minOccurs="0" maxOccurs="1"/>
													<!-- XXX TODO Name is required really -->
													<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
													<xs:element name="ID" type="String" minOccurs="0" maxOccurs="1" />
													<xs:element name="Type" type="DataTypeID" minOccurs="0" maxOccurs="1" />
													<xs:element name="SubType" type="SubType" minOccurs="0" maxOccurs="1" />
													<xs:element name="References" type="Token" minOccurs="0" maxOccurs="1" />
												</xs:all>
												<xs:attribute name="ID" type="Token" use="required" />
												<xs:attribute name="Type" type="DataTypeID" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="SubTypes" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="SubType" maxOccurs="unbounded">
											<xs:complexType>
												<xs:all>
													<xs:element name="Name" type="String" minOccurs="0" maxOccurs="1" />
													<!-- XXX TODO Name is required really -->
													<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
													<xs:element name="CType" type="String" />
													<xs:element name="CodeName" type="CodeNameType" minOccurs="0" maxOccurs="1" />
													<xs:element name="MandatoryAttributes" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="MandatoryAttribute" type="Token" maxOccurs="unbounded" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:all>
												<xs:attribute name="ID" type="Token" use="required" />
												<xs:attribute name="Width" type="Shekel" use="optional" default="1" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ID" type="Token" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Field">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="String" minOccurs="0" maxOccurs="1"/>
				<!-- XXX TODO name not really optional -->
				<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="ID" type="Token" use="required" />
			<xs:attribute name="Width" type="Shekel" use="optional" default="1" />
			<xs:attribute name="Type" type="DataTypeID" use="required" />
			<xs:attribute name="SubType" type="SubType" use="optional" />
			<xs:anyAttribute namespace="##any" processContents="lax"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="NRFPacket">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nrf:Field" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Message">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Flags">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Flag" maxOccurs="8" minOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="Token">
											<xs:attribute name="Mandatory" type="xs:boolean" use="optional" />
											<xs:attribute name="Negate" type="xs:boolean" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayloadStructure">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="nrf:Field" maxOccurs="unbounded" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="SubType" type="Token" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="MessageType">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="String" />
				<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
				<xs:element name="CodeName" type="CodeNameType" />
				<xs:element name="SubTypes" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SubType" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="String" minOccurs="0" maxOccurs="1" />
										<!-- XXX TODO name isnt really optional -->
										<xs:element name="Description" type="String" minOccurs="0" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="ID" type="Token" use="required" />
									<xs:attribute name="CodeName" type="CodeNameType" use="required" />
									<xs:attribute name="SequenceOffset" type="Shekel" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Messages">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="nrf:Message" maxOccurs="unbounded" minOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ID" type="Token" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="MessageTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nrf:MessageType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kieransimkin/TangleNet-ProtocolSchema/NRFProtocol.xml
<?xml version="1.0" encoding="UTF-8"?>
<NRFProtocol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NRFProtocol.xsd">
	<BitfieldTypes>
		<BitfieldType ID="MESSAGE_FLAGS" Width="1">
			<Name><![CDATA[MessageFlags]]></Name>
			<Description><![CDATA[

			]]></Description>
			<Bits>
				<Bit ID="BEGIN"><Description></Description></Bit>
				<Bit ID="END"><Description></Description></Bit>
				<Bit ID="ECHO"><Description></Description></Bit>
				<Bit ID="SIGNED"><Description></Description></Bit>
				<Bit ID="RETRANSMIT"><Description></Description></Bit>
				<Bit ID="FORWARDED"><Description></Description></Bit>
				<Bit ID="CHRONICLE"><Description></Description></Bit>
				<Bit ID="PLEASE_SIGN"><Description></Description></Bit>
			</Bits>
		</BitfieldType>
		<BitfieldType ID="TEMPORAL_ACCURACY" Width="1">
			<Name><![CDATA[TemporalAccuracy]]></Name>
			<Description><![CDATA[

			]]></Description>
			<Bits>
				<Bit ID="RTC"><Description></Description></Bit>
				<Bit ID="TCXO"><Description></Description></Bit>
				<Bit ID="NTP"><Description></Description></Bit>
				<Bit ID="GPS"><Description></Description></Bit>
				<Bit ID="RF"><Description></Description></Bit>
				<Bit ID="RUBIDIUM"><Description></Description></Bit>
				<Bit ID="CAESEUM"><Description></Description></Bit>
				<Bit ID="TIMELORD"><Description></Description></Bit>
			</Bits>
		</BitfieldType>
		<BitfieldType ID="SPACIAL_ACCURACY" Width="1">
			<Name><![CDATA[SpacialAccuracy]]></Name>
			<Description><![CDATA[

			]]></Description>
			<Bits>
				<Bit ID="GPS"><Description></Description></Bit>
				<Bit ID="WIFI"><Description></Description></Bit>
				<Bit ID="DEDUCED"><Description></Description></Bit>
				<Bit ID="CONFIRMED"><Description></Description></Bit>
				<Bit ID="CELESTIAL"><Description></Description></Bit>
				<Bit ID="MAGNETIC"><Description></Description></Bit>
				<Bit ID="ACCELEROMETER"><Description></Description></Bit>
				<Bit ID="KNOWN_FIXED"><Description></Description></Bit>
			</Bits>
		</BitfieldType>
	</BitfieldTypes>
	<Enumerations>
		<Enumeration ID="COLLISION_PARTICIPANT">
			<Name><![CDATA[CollisionParticipant]]></Name>
			<Description><![CDATA[

			]]></Description>
			<Option ID="IMPOSTOR"><Description></Description></Option>
			<Option ID="VICTIM"><Description></Description></Option>
		</Enumeration>
		<Enumeration ID="HANDEDNESS">
			<Name><![CDATA[Handedness]]></Name>
			<Description><![CDATA[

			]]></Description>
			<Option ID="LEFT"><Description></Description></Option>
			<Option ID="RIGHT"><Description></Description></Option>
		</Enumeration>
		<Enumeration ID="SEQUENCE_PADDING">
			<Name><![CDATA[SequencePadding]]></Name>
			<Description><![CDATA[

			]]></Description>
			<Option ID="FULL_SEQUENCE_UNKNOWN"><Description></Description></Option>
			<Option ID="FULL_SEQUENCE"><Description></Description></Option>
		</Enumeration>
		<Enumeration ID="TIMESPAN_LENGTH">
			<Name><![CDATA[TimespanLength]]></Name>
			<Description><![CDATA[

			]]></Description>
			<Option ID="MILLISECONDS"><Description></Description></Option>"
			<Option ID="SECONDS"><Description></Description></Option>"
			<Option ID="HOURS"><Description></Description></Option>"
			<Option ID="DAYS"><Description></Description></Option>"
			<Option ID="WEEKS"><Description></Description></Option>"
			<Option ID="MONTHS"><Description></Description></Option>"
			<Option ID="YEARS"><Description></Description></Option>"
			<Option ID="TICKS"><Description></Description></Option>"
		</Enumeration>
		<Enumeration ID="TIME_PRECISION">
			<Name><![CDATA[TimePrecision]]></Name>
			<Description><![CDATA[

			]]></Description>
			<Option ID="MICROSECONDS"><Description></Description></Option>
			<Option ID="MILLISECONDS"><Description></Description></Option>
			<Option ID="SECONDS"><Description></Description></Option>
		</Enumeration>
	</Enumerations>
	<Types>
		<Type ID="UINT">
			<Name><![CDATA[UInt]]></Name>
			<Description><![CDATA[

			]]></Description>
			<CType>uint8_t</CType>
			<MaxWidth>8</MaxWidth>
			<DefaultWidth>1</DefaultWidth>
			<InvalidWidths>
				<InvalidWidth>3</InvalidWidth>
				<InvalidWidth>5</InvalidWidth>
				<InvalidWidth>6</InvalidWidth>
				<InvalidWidth>7</InvalidWidth>
			</InvalidWidths>
			<SubTypes>
				<SubType ID="UINT16" Width="2">
					<Name><![CDATA[UInt16]]></Name>
					<CType>uint16_t</CType>
				</SubType>
				<SubType ID="UINT32" Width="4">
					<Name><![CDATA[UInt32]]></Name>
					<CType>uint32_t</CType>
				</SubType>
				<SubType ID="UINT64" Width="8">
					<Name><![CDATA[UInt64]]></Name>
					<CType>uint64_t</CType>
				</SubType>
			</SubTypes>
		</Type>
		<Type ID="STRING">
			<Name><![CDATA[String]]></Name>
			<Description><![CDATA[

			]]></Description>
		
			<CType>char[LENGTH+1]</CType>
		</Type>
		<Type ID="BINARY">
			<Name><![CDATA[Binary]]></Name>
			<Description><![CDATA[

			]]></Description>
			<CType>uint8_t[LENGTH]</CType>
		</Type>
		<Type ID="ENUM">
			<Name><![CDATA[Enumeration]]></Name>
			<Description><![CDATA[

				]]></Description>
			<MaxWidth>2</MaxWidth>
			<Attributes>
				<Attribute ID="SubType"><References>Enumerations</References><Description>Enumeration</Description></Attribute>
			</Attributes>
			<CType>uint8_t</CType>
			<DefaultWidth>1</DefaultWidth>
			<SubTypes>
				<SubType ID="WIDE_ENUM" Width="2"><CType>uint16_t</CType></SubType>
			</SubTypes>
		</Type>
		<Type ID="BITFIELD">
			<Name><![CDATA[Bitfield]]></Name>
			<Description><![CDATA[

			]]></Description>
			<MaxWidth>2</MaxWidth>
			<DefaultWidth>1</DefaultWidth>
			<Attributes>
				<Attribute ID="SubType"><References>BitfieldTypes</References><Description>Bitfield Type</Description></Attribute>
			</Attributes>
			<CType>uint8_t</CType>
			<SubTypes>
				<SubType ID="WIDE_BITFIELD" Width="2"><CType>uint16_t</CType></SubType>
			</SubTypes>
		</Type>
		<Type ID="ECDSA_PUBLIC">
			<Name><![CDATA[ecdsaPublic]]></Name>
			<Description><![CDATA[

				]]></Description>
			<MinWidth>21</MinWidth>
			<MaxWidth>21</MaxWidth>
			<CType>uint8_t[21]</CType>
		</Type>
		<Type ID="ECDSA_HALFSIGN">
			<Name><![CDATA[ecdsaHalfSign]]></Name>
			<Description><![CDATA[

				]]></Description>
			<Attributes>
				<Attribute ID="Handedness" Type="ENUM"><ID>HANDEDNESS</ID><Description>Enumeration</Description></Attribute>
			</Attributes>
			<MinWidth>20</MinWidth>
			<MaxWidth>20</MaxWidth>
			<CType>uint8_t[20]</CType>
		</Type>
		<Type ID="KNOT_LINK_ID">
			<Name><![CDATA[KnotLinkID]]></Name>
			<Description><![CDATA[

				]]></Description>
			<MinWidth>3</MinWidth>
			<MaxWidth>3</MaxWidth>
			<CType>uint8_t[3]</CType>
		</Type>
		<Type ID="SUBTYPE">
			<Name><![CDATA[MessageSubtype]]></Name>
			<Description><![CDATA[

				]]></Description>
			<CType>uint8_t</CType>
			<MaxWidth>1</MaxWidth>
		</Type>
		<Type ID="SEQUENCE">
			<Name><![CDATA[Sequence]]></Name>
			<Description><![CDATA[

				]]></Description>
			<CType>uint8_t</CType>
			<DefaultWidth>1</DefaultWidth>
			<MaxWidth>4</MaxWidth>
			<InvalidWidths>
				<InvalidWidth>2</InvalidWidth>
				<InvalidWidth>3</InvalidWidth>
			</InvalidWidths>
			<Attributes>
				<Attribute ID="PaddingField" Type="FIELD"><Type>ENUM</Type><SubType>SEQUENCE_PADDING</SubType><Description></Description></Attribute>
			</Attributes>
			<SubTypes>
				<SubType ID="FULL_SEQUENCE" Width="4"><CType>uint32_t</CType></SubType>
			</SubTypes>
		</Type>
		<Type ID="TIMESTAMP">
			<Name><![CDATA[Timestamp]]></Name>
			<Description><![CDATA[

				]]></Description>
			<ValidWidths>
				<ValidWidth>4</ValidWidth>
				<ValidWidth>8</ValidWidth>
			</ValidWidths>
			<CType>uint32_t</CType>
			<DefaultWidth>4</DefaultWidth>
			<Attributes>
				<Attribute ID="PrecisionField" Type="FIELD"><Type>ENUM</Type><SubType>TIME_PRECISION</SubType><Description></Description></Attribute>
				<Attribute ID="AccuracyField" Type="FIELD"><Type>BITFIELD</Type><SubType>TEMPORAL_ACCURACY</SubType><Description></Description></Attribute>
			</Attributes>
			<SubTypes>
				<SubType ID="WIDE_TIMESTAMP" Width="8"><CType>uint64_t</CType></SubType>
				<SubType ID="PRECISE_TIMESTAMP" Width="8"><CType>uint64_t</CType></SubType>
				<SubType ID="VARIABLE_WIDE_TIMESTAMP" Width="8"><CType>uint64_t</CType><MandatoryAttributes><Attribute>PrecisionField</Attribute></MandatoryAttributes></SubType>
				<SubType ID="VARIABLE_TIMESTAMP" Width="4"><CType>uint64_t</CType><MandatoryAttributes><Attribute>PrecisionField</Attribute></MandatoryAttributes></SubType>
			</SubTypes>
		</Type>
		<Type ID="TIMESPAN">
			<Name><![CDATA[Timespan]]></Name>
			<Description><![CDATA[

				]]></Description>
			<ValidWidths>
				<ValidWidth>1</ValidWidth>
				<ValidWidth>2</ValidWidth>
				<ValidWidth>4</ValidWidth>
				<ValidWidth>8</ValidWidth>
			</ValidWidths>
			<CType>uint8_t</CType>
			<DefaultWidth>1</DefaultWidth>
			<Attributes>
				<Attribute ID="FixedLength" Type="ENUM"><ID>TIMESPAN_LENGTH</ID><Description>Enumeration</Description></Attribute>
				<Attribute ID="LengthField" Type="FIELD"><Type>ENUM</Type><SubType>TIMESPAN_LENGTH</SubType><Description></Description></Attribute>
				<Attribute ID="PrecisionField" Type="FIELD"><Type>ENUM</Type><SubType>TIME_PRECISION</SubType><Description></Description></Attribute>
				<Attribute ID="FixedPrecision" Type="ENUM"><ID>TIME_PRECISION</ID><Description></Description></Attribute>
				<Attribute ID="AccuracyField" Type="FIELD"><Type>BITFIELD</Type><SubType>TEMPORAL_ACCURACY</SubType><Description></Description></Attribute>
			</Attributes>
			<SubTypes>
				<SubType ID="TIMESPAN" Width="1"><CType>uint8_t</CType><MandatoryAttributes><Attribute>LengthField</Attribute></MandatoryAttributes></SubType>
				<SubType ID="TIMESPAN16" Width="2"><CType>uint16_t</CType><MandatoryAttributes><Attribute>LengthField</Attribute></MandatoryAttributes></SubType>
				<SubType ID="TIMESPAN32" Width="4"><CType>uint32_t</CType><MandatoryAttributes><Attribute>LengthField</Attribute></MandatoryAttributes></SubType>
